In [3]:
import numpy as np

In [4]:
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    # TODO: Compute and return softmax(x)
    return np.exp(x)/np.sum(np.exp(x))
logits = np.array([[1, 2, 3, 6],[2, 4, 5, 6],[3, 8, 7, 6]])
print(softmax(logits))

[[  4.89907947e-04   1.33170787e-03   3.61995731e-03   7.27087861e-02]
 [  1.33170787e-03   9.84006416e-03   2.67480676e-02   7.27087861e-02]
 [  3.61995731e-03   5.37249300e-01   1.97642972e-01   7.27087861e-02]]
